<a href="https://colab.research.google.com/github/Amri1003/Machine_Learning_Projects/blob/main/AprioriAndECLAT_Algo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
data=pd.read_csv('Market_Basket_Optimisation.csv',header=None)

In [31]:
# import warning
import warnings
warnings.filterwarnings('ignore')

In [32]:
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
import warnings
warnings.filterwarnings('ignore')

## convert this data into list of list

In [34]:
data.shape[0]

7501

In [35]:
# convert this df into list of list
transactions=[]
for i in range(data.shape[0]):
    transactions.append([str(data.values[i,j]) for j in range(data.shape[1]) if str(data.values[i,j])!='nan'])

In [36]:
transactions

[['shrimp',
  'almonds',
  'avocado',
  'vegetables mix',
  'green grapes',
  'whole weat flour',
  'yams',
  'cottage cheese',
  'energy drink',
  'tomato juice',
  'low fat yogurt',
  'green tea',
  'honey',
  'salad',
  'mineral water',
  'salmon',
  'antioxydant juice',
  'frozen smoothie',
  'spinach',
  'olive oil'],
 ['burgers', 'meatballs', 'eggs'],
 ['chutney'],
 ['turkey', 'avocado'],
 ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea'],
 ['low fat yogurt'],
 ['whole wheat pasta', 'french fries'],
 ['soup', 'light cream', 'shallot'],
 ['frozen vegetables', 'spaghetti', 'green tea'],
 ['french fries'],
 ['eggs', 'pet food'],
 ['cookies'],
 ['turkey', 'burgers', 'mineral water', 'eggs', 'cooking oil'],
 ['spaghetti', 'champagne', 'cookies'],
 ['mineral water', 'salmon'],
 ['mineral water'],
 ['shrimp',
  'chocolate',
  'chicken',
  'honey',
  'oil',
  'cooking oil',
  'low fat yogurt'],
 ['turkey', 'eggs'],
 ['turkey',
  'fresh tuna',
  'tomatoes',
  'spaghetti',
  'mineral water',
  'black tea',
  'salmon',
  'eggs',
  'chicken',
  'extra dark chocolate'],
 ['meatballs', 'milk', 'honey', 'french fries', 'protein bar'],
 ['red wine', 'shrimp', 'pasta', 'pepper', 'eggs', 'chocolate', 'shampoo'],
 ['rice', 'sparkling water'],
 ['spaghetti', 'mineral water', 'ham', 'body spray', 'pancakes', 'green tea'],
 ['burgers',
  'grated cheese',
  'shrimp',
  'pasta',
  'avocado',
  'honey',
  'white wine',
  'toothpaste'],
 ['eggs'],
 ['parmesan cheese', 'spaghetti', 'soup', 'avocado', 'milk', 'fresh bread'],
 ['ground beef',
  'spaghetti',
  'mineral water',
  'milk',
  'energy bar',
  'black tea',
  'salmon',
  'frozen smoothie',
  'escalope'],
 ['sparkling water'],
 ['mineral water', 'eggs', 'chicken', 'chocolate', 'french fries'],
 ['frozen vegetables', 'spaghetti', 'yams', 'mineral water'],
 ['herb & pepper', 'tomato sauce', 'light cream', 'magazines'],
 ['mineral water', 'chocolate', 'avocado', 'eggs'],
 ['turkey', 'french fries', 'strawberries'],
 ['frozen vegetables', 'strong cheese', 'chocolate'],
 ['cookies'],
 ['pickles', 'spaghetti', 'salmon', 'escalope'],
 ['energy bar', 'french fries'],
 ['red wine', 'ground beef', 'mineral water'],
 ['mineral water', 'cake', 'cottage cheese'],
 ['pickles', 'champagne', 'green tea'],
 ['spaghetti'],
 ['fresh tuna',
  'frozen vegetables',
  'spaghetti',
  'mineral water',
  'honey',
  'whole wheat rice',
  'frozen smoothie',
  'escalope'],
 ['spaghetti'],
 ['soup', 'meatballs', 'hot dogs', 'sparkling water'],
 ['escalope'],
 ['soup',
  'avocado',
  'french fries',
  'hot dogs',
  'brownies',
  'body spray',
  'pancakes',
  'green tea'],
 ['mineral water', 'chicken', 'cereals', 'clothes accessories'],
 ['mineral water', 'bug spray'],
 ['avocado', 'muffins'],
 ['burgers', 'black tea', 'green tea'],
 ['spaghetti', 'chocolate', 'brownies', 'white wine', 'green tea'],
 ['fresh tuna', 'mineral water', 'eggs'],
 ['spaghetti', 'muffins'],
 ['spaghetti', 'chocolate'],
 ['french fries', 'escalope', 'champagne'],
 ['tomato sauce', 'light mayo'],
 ['turkey',
  'fresh tuna',
  'frozen vegetables',
  'tomatoes',
  'ground beef',
  'spaghetti',
  'mineral water',
  'chocolate',
  'soup',
  'milk',
  'olive oil'],
 ['eggs', 'cookies'],
 ['soup',
  'chicken',
  'gums',
  'soda',
  'body spray',
  'energy drink',
  'green tea'],
 ['turkey',
  'frozen vegetables',
  'mineral water',
  'cider',
  'cooking oil',
  'green tea'],
 ['spaghetti'],
 ['clothes accessories'],
 ['energy drink'],
 ['soup', 'bug spray', 'shallot', 'protein bar', 'green tea'],
 ['turkey', 'eggs'],
 ['french fries'],
 ['chocolate', 'milk'],
 ['herb & pepper',
  'whole wheat pasta',
  'ground beef',
  'mineral water',
  'avocado',
  'cider',
  'whole wheat rice'],
 ['cookies'],
 ['shrimp', 'pasta'],
 ['grated cheese', 'herb & pepper', 'tomatoes', 'tomato sauce', 'corn'],
 ['burgers', 'escalope', 'shallot'],
 ['cookies'],
 ['yogurt cake'],
 ['soup', 'eggs'],
 ['cookies'],
 ['mineral water', 'chocolate', 'low fat yogurt'],
 ['eggs', 'strawberries'],
 ['grated cheese', 'ground beef', 'spaghetti', 'mineral water', 'white wine'],
 ['mint'],
 ['eggs', 'cake', 'french fries'],
 ['burgers', 'spaghetti', 'milk', 'french fries', 'green tea'],
 ['mineral water', 'energy bar', 'butter', 'french fries'],
 ['burgers',
  'grated cheese',
  'herb & pepper',
  'mineral water',
  'eggs',
  'cooking oil'],
 ['energy bar'],
 ['energy bar', 'energy drink'],
 ['chocolate', 'frozen smoothie'],
 ['low fat yogurt'],
 ['asparagus', 'salad'],
 ['burgers', 'french fries', 'low fat yogurt', 'green tea'],
 ['low fat yogurt'],
 ['burgers',
  'herb & pepper',
  'shrimp',
  'pasta',
  'spaghetti',
  'mineral water',
  'meatballs',
  'olive oil',
  'energy bar',
  'french wine',
  'eggs',
  'salt'],
 ['champagne', 'low fat yogurt'],
 ['champagne'],
 ['burgers', 'almonds', 'eggs', 'french fries', 'cookies', 'green tea'],
 ['ham', 'soup', 'escalope', 'body spray'],
 ['turkey',
  'ham',
  'frozen vegetables',
  'pepper',
  'oil',
  'extra dark chocolate',
  'tea',
  'magazines'],
 ['muffins', 'eggs', 'cookies'],
 ['cookies'],
 ['frozen vegetables',
  'whole wheat pasta',
  'ground beef',
  'spaghetti',
  'chocolate',
  'green tea'],
 ['mineral water', 'barbecue sauce', 'chocolate'],
 ['burgers',
  'herb & pepper',
  'energy bar',
  'almonds',
  'eggs',
  'corn',
  'mayonnaise',
  'zucchini'],
 ['turkey',
  'burgers',
  'ground beef',
  'chocolate',
  'soup',
  'almonds',
  'eggs',
  'hot dogs',
  'cottage cheese'],
 ['ham', 'spaghetti', 'chocolate', 'eggs'],
 ['ground beef', 'energy bar', 'pet food', 'carrots', 'protein bar'],
 ['ground beef',
  'tomato sauce',
  'spaghetti',
  'mineral water',
  'almonds',
  'eggs'],
 ['mineral water', 'olive oil', 'gums', 'cooking oil'],
 ['shrimp',
  'pasta',
  'mineral water',
  'soup',
  'avocado',
  'milk',
  'olive oil',
  'green grapes',
  'eggs',
  'bug spray'],
 ['shrimp',
  'pasta',
  'soup',
  'cake',
  'cooking oil',
  'chicken',
  'light mayo',
  'low fat yogurt'],
 ['spaghetti',
  'mineral water',
  'chocolate',
  'french fries',
  'champagne',
  'escalope',
  'mushroom cream sauce',
  'fresh bread'],
 ['shrimp', 'pasta', 'mineral water', 'eggs'],
 ['burgers', 'oil', 'tomato juice', 'fresh bread'],
 ['french wine', 'eggs', 'chocolate', 'low fat yogurt'],
 ['chicken', 'eggs', 'french fries', 'pancakes'],
 ['turkey', 'herb & pepper', 'salmon', 'white wine', 'candy bars'],
 ['grated cheese',
  'spaghetti',
  'olive oil',
  'eggs',
  'french fries',
  'green tea'],
 ['mineral water', 'energy bar'],
 ['eggs', 'french fries'],
 ['burgers',
  'tomatoes',
  'mineral water',
  'soup',
  'milk',
  'almonds',
  'eggs',
  'chocolate',
  'tomato juice'],
 ['muffins'],
 ['pasta'],
 ['tomatoes', 'spaghetti', 'frozen smoothie'],
 ['ground beef', 'spaghetti', 'milk'],
 ['french fries'],
 ['chocolate', 'milk'],
 ['burgers',
  'shrimp',
  'pasta',
  'frozen vegetables',
  'spaghetti',
  'mineral water',
  'milk',
  'eggs',
  'chocolate',
  'french fries',
  'pancakes',
  'low fat yogurt'],
 ['ground beef', 'mineral water', 'antioxydant juice', 'protein bar'],
 ['grated cheese',
  'whole wheat pasta',
  'ground beef',
  'spaghetti',
  'cake',
  'energy drink'],
 ['grated cheese'],
 ['pancakes'],
 ['frozen smoothie'],
 ['carrots', 'green tea'],
 ['chocolate'],
 ['turkey',
  'burgers',
  'chocolate',
  'olive oil',
  'eggs',
  'cooking oil',
  'corn'],
 ['frozen vegetables',
  'tomatoes',
  'pepper',
  'spaghetti',
  'mineral water',
  'pancakes',
  'chicken',
  'chili',
  'tea',
  'french fries',
  'tomato juice',
  'fresh bread'],
 ['cookies'],
 ['ground beef'],
 ['turkey', 'eggs', 'chocolate', 'frozen smoothie', 'tomato juice'],
 ['frozen vegetables', 'cooking oil', 'mashed potato'],
 ['frozen vegetables',
  'ground beef',
  'tomato sauce',
  'mineral water',
  'meatballs',
  'olive oil',
  'light cream',
  'tomato juice'],
 ['red wine',
  'spaghetti',
  'mineral water',
  'soup',
  'milk',
  'eggs',
  'cake',
  'gums',
  'cooking oil',
  'chocolate',
  'frozen smoothie'],
 ['chocolate',
  'tomatoes',
  'spaghetti',
  'mineral water',
  'avocado',
  'milk',
  'olive oil',
  'eggs',
  'rice',
  'french fries',
  'brownies'],
 ['chocolate',
  'shrimp',
  'pasta',
  'frozen vegetables',
  'ground beef',
  'mineral water',
  'nonfat milk',
  'eggs'],
 ['turkey',
  'shrimp',
  'pasta',
  'pepper',
  'spaghetti',
  'mineral water',
  'eggs',
  'chicken',
  'french fries'],
 ['cookies'],
 ['turkey', 'tomatoes', 'cake'],
 ['yams',
  'mineral water',
  'soup',
  'milk',
  'pancakes',
  'whole wheat rice',
  'barbecue sauce',
  'carrots',
  'chocolate',
  'champagne'],
 ['rice'],
 ['chocolate', 'milk'],
 ['shrimp', 'pasta', 'frozen vegetables', 'water spray'],
 ['burgers', 'mineral water', 'milk', 'eggs', 'whole wheat rice', 'mint'],
 ['mineral water', 'vegetables mix', 'cake', 'frozen smoothie', 'brownies'],
 ['cookies'],
 ['shrimp', 'pasta', 'chicken', 'chocolate bread'],
 ['shallot'],
 ['shrimp', 'pasta', 'spaghetti', 'eggs', 'hot dogs', 'green tea'],
 ['burgers'],
 ['red wine',
  'ground beef',
  'spaghetti',
  'mineral water',
  'milk',
  'olive oil',
  'strong cheese',
  'light cream',
  'cooking oil'],
 ['burgers',
  'grated cheese',
  'spaghetti',
  'avocado',
  'milk',
  'oil',
  'french fries'],
 ['herb & pepper',
  'whole wheat pasta',
  'ground beef',
  'mineral water',
  'olive oil'],
 ['shrimp', 'pasta', 'yams', 'milk', 'chocolate'],
 ['butter', 'green tea'],
 ['light mayo'],
 ['low fat yogurt'],
 ['herb & pepper', 'shrimp', 'pasta', 'spaghetti', 'milk'],
 ['burgers', 'eggs'],
 ['turkey',
  'herb & pepper',
  'ground beef',
  'soup',
  'avocado',
  'milk',
  'black tea',
  'eggs',
  'barbecue sauce',
  'carrots',
  'cookies',
  'tomato juice',
  'fresh bread'],
 ['cookies'],
 ['escalope'],
 ['pepper', 'french fries', 'strawberries', 'pancakes', 'low fat yogurt'],
 ['frozen vegetables', 'yams', 'chicken', 'honey', 'light mayo'],
 ['chocolate', 'champagne'],
 ['herb & pepper', 'honey', 'cake', 'rice', 'protein bar'],
 ['burgers',
  'chocolate',
  'frozen vegetables',
  'ground beef',
  'mineral water',
  'milk',
  'light mayo',
  'asparagus'],
 ['chocolate', 'mineral water', 'corn', 'cottage cheese', 'green tea'],
 ['muffins'],
 ['ham', 'french wine', 'escalope'],
 ['spaghetti', 'milk', 'whole wheat rice', 'mint green tea'],
 ['chocolate', 'body spray'],
 ['frozen vegetables', 'french fries', 'hot dogs'],
 ['candy bars'],
 ['burgers',
  'shrimp',
  'pasta',
  'milk',
  'green tea',
  'french fries',
  'cookies',
  'white wine'],
 ['parmesan cheese', 'ground beef'],
 ['pancakes', 'whole wheat rice', 'candy bars'],
 ['eggs', 'eggplant', 'cookies'],
 ['frozen vegetables', 'mineral water'],
 ['chocolate'],
 ['turkey', 'spaghetti', 'milk', 'whole wheat rice', 'chocolate'],
 ['whole wheat pasta',
  'ground beef',
  'spaghetti',
  'soup',
  'meatballs',
  'chicken',
  'blueberries',
  'cooking oil',
  'champagne',
  'yogurt cake',
  'protein bar'],
 ['cooking oil', 'tomato juice'],
 ['frozen vegetables', 'milk', 'eggs', 'french fries', 'green tea'],
 ['fresh tuna',
  'spaghetti',
  'olive oil',
  'french wine',
  'eggs',
  'french fries',
  'champagne',
  'pancakes',
  'light mayo'],
 ['red wine', 'honey', 'hot dogs'],
 ['milk', 'bacon', 'eggs', 'french fries', 'fresh bread'],
 ['french fries', 'yogurt cake'],
 ['milk'],
 ['french fries'],
 ['chocolate'],
 ['burgers', 'ham', 'red wine'],
 ['shrimp',
  'pasta',
  'tomatoes',
  'energy bar',
  'french wine',
  'antioxydant juice',
  'french fries',
  'frozen smoothie',
  'brownies'],
 ['green tea'],
 ['low fat yogurt'],
 ['turkey',
  'spaghetti',
  'mineral water',
  'soup',
  'spinach',
  'soda',
  'energy drink',
  'salt'],
 ['turkey', 'eggs'],
 ['bug spray', 'hot dogs'],
 ['oil'],
 ['soup',
  'energy bar',
  'chicken',
  'eggs',
  'cake',
  'french fries',
  'body spray',
  'strawberries'],
 ['spaghetti', 'chocolate', 'yogurt cake'],
 ['turkey', 'mineral water', 'meatballs'],
 ['ground beef',
  'mineral water',
  'chocolate',
  'fromage blanc',
  'bacon',
  'hot dogs'],
 ['frozen vegetables', 'mineral water', 'vegetables mix', 'escalope'],
 ['herb & pepper', 'red wine', 'tomatoes'],
 ['whole wheat pasta', 'olive oil', 'cereals', 'brownies', 'green tea'],
 ['cookies'],
 ['olive oil', 'cookies', 'mushroom cream sauce'],
 ['ground beef', 'pancakes', 'cooking oil', 'gluten free bar', 'light mayo'],
 ['mineral water', 'french fries'],
 ['herb & pepper'],
 ['salmon'],
 ['eggs', 'escalope'],
 ['mineral water', 'tomato juice'],
 ['mineral water'],
 ['shrimp', 'mineral water', 'soup', 'black tea'],
 ['cake', 'frozen smoothie'],
 ['turkey',
  'burgers',
  'grated cheese',
  'tomatoes',
  'chocolate',
  'fromage blanc',
  'honey',
  'whole wheat rice'],
 ['frozen vegetables',
  'ground beef',
  'mineral water',
  'olive oil',
  'pancakes'],
 ['turkey',
  'burgers',
  'ground beef',
  'milk',
  'olive oil',
  'cake',
  'fresh bread'],
 ['whole wheat pasta',
  'ground beef',
  'spaghetti',
  'yams',
  'mineral water',
  'soup',
  'chutney',
  'cereals',
  'energy drink',
  'protein bar'],
 ['eggs', 'whole wheat rice', 'cake', 'green tea', 'escalope'],
 ['ground beef', 'yams', 'soup', 'avocado', 'salmon', 'green tea'],
 ['milk'],
 ['spaghetti', 'chocolate'],
 ['whole wheat pasta', 'honey'],
 ['whole wheat pasta', 'green tea'],
 ['spaghetti', 'meatballs', 'vegetables mix', 'chocolate'],
 ['eggs', 'low fat yogurt'],
 ['fresh tuna',
  'shrimp',
  'pasta',
  'mineral water',
  'olive oil',
  'eggs',
  'cake',
  'brownies',
  'tomato juice'],
 ['mineral water', 'green grapes', 'hot dogs', 'fresh bread'],
 ['frozen vegetables', 'meatballs', 'eggs', 'chocolate'],
 ['chocolate'],
 ['meatballs', 'milk'],
 ['low fat yogurt'],
 ['green tea'],
 ['escalope', 'pasta'],
 ['pepper',
  'chocolate',
  'olive oil',
  'french wine',
  'salmon',
  'rice',
  'light mayo',
  'fresh bread',
  'magazines'],
 ['red wine',
  'french wine',
  'vegetables mix',
  'rice',
  'clothes accessories',
  'hot dogs',
  'green tea'],
 ['burgers',
  'dessert wine',
  'spaghetti',
  'chicken',
  'cake',
  'protein bar',
  'green tea'],
 ['french wine', 'cake', 'fresh bread'],
 ['burgers', 'frozen vegetables', 'flax seed', 'eggs'],
 ['red wine'],
 ['pepper', 'mineral water', 'energy bar', 'green grapes'],
 ['milk', 'eggs', 'cake', 'chocolate', 'french fries', 'green tea'],
 ['french fries'],
 ['almonds'],
 ['burgers', 'mineral water', 'green tea'],
 ['milk', 'pancakes'],
 ['pancakes', 'eggs', 'salt', 'tomato juice'],
 ['mineral water'],
 ['ham', 'spaghetti', 'mineral water', 'olive oil'],
 ['salt', 'tomato juice', 'fresh bread'],
 ['spaghetti', 'mushroom cream sauce'],
 ['spaghetti', 'mineral water', 'eggs', 'pet food'],
 ['frozen vegetables', 'spaghetti'],
 ['energy drink'],
 ['muffins'],
 ['turkey', 'milk'],
 ['cookies'],
 ['chocolate'],
 ['spaghetti',
  'mineral water',
  'eggs',
  'cooking oil',
  'chocolate',
  'escalope'],
 ['shrimp', 'frozen vegetables', 'pepper', 'spaghetti', 'green tea'],
 ['burgers',
  'fresh tuna',
  'red wine',
  'mineral water',
  'french fries',
  'hand protein bar',
  'low fat yogurt'],
 ['pancakes', 'eggs', 'energy drink', 'fresh bread'],
 ['strong cheese',
  'salmon',
  'green tea',
  'french fries',
  'frozen smoothie',
  'hot dogs'],
 ['grated cheese',
  'shrimp',
  'pasta',
  'tomatoes',
  'milk',
  'frozen smoothie',
  'sandwich'],
 ['herb & pepper', 'whole wheat pasta', 'olive oil', 'pancakes', 'eggs'],
 ['spaghetti', 'antioxydant juice'],
 ['chocolate', 'milk', 'almonds', 'eggs', 'strawberries', 'white wine'],
 ['french fries', 'strawberries'],
 ['mineral water'],
 ['eggs'],
 ['escalope'],
 ['cake'],
 ['whole wheat pasta', 'antioxydant juice', 'body spray', 'green tea'],
 ['mineral water', 'oil', 'frozen smoothie'],
 ['french fries', 'champagne'],
 ['chocolate', 'french fries'],
 ['frozen vegetables', 'spaghetti', 'eggs'],
 ['hot dogs'],
 ['chocolate', 'cookies'],
 ['pancakes'],
 ['shrimp', 'butter', 'chicken', 'salmon'],
 ['chocolate', 'cookies', 'babies food'],
 ['pepper', 'spaghetti', 'cake', 'chocolate', 'french fries', 'fresh bread'],
 ['avocado', 'oil', 'cereals', 'french fries'],
 ['herb & pepper',
  'spaghetti',
  'mineral water',
  'spinach',
  'eggs',
  'oil',
  'cooking oil',
  'green tea',
  'shampoo',
  'tomato juice',
  'low fat yogurt'],
 ['herb & pepper',
  'frozen vegetables',
  'ground beef',
  'pepper',
  'spaghetti',
  'mint green tea',
  'french fries'],
 ['french fries'],
 ['green tea', 'tomato juice'],
 ['eggs', 'whole wheat rice', 'chocolate'],
 ['grated cheese',
  'herb & pepper',
  'red wine',
  'spaghetti',
  'mineral water',
  'salmon',
  'eggs',
  'cooking oil',
  'green tea'],
 ['french fries',
  'cookies',
  'shallot',
  'tomato juice',
  'fresh bread',
  'low fat yogurt'],
 ['burgers', 'fresh tuna', 'spaghetti', 'muffins', 'honey'],
 ['herb & pepper', 'ground beef', 'spaghetti', 'eggs', 'chicken'],
 ['grated cheese', 'muffins', 'tomato juice', 'mayonnaise'],
 ['whole wheat pasta',
  'yams',
  'mineral water',
  'muffins',
  'frozen smoothie',
  'hot dogs',
  'energy drink'],
 ['burgers',
  'spaghetti',
  'soup',
  'milk',
  'olive oil',
  'salmon',
  'eggs',
  'blueberries'],
 ['chocolate', 'champagne', 'magazines'],
 ['frozen vegetables',
  'spaghetti',
  'yams',
  'mineral water',
  'french wine',
  'green grapes',
  'rice',
  'chocolate'],
 ['tomato sauce', 'chocolate'],
 ['milk', 'eggs'],
 ['pet food'],
 ['yogurt cake'],
 ['green tea'],
 ['escalope', 'pasta'],
 ['herb & pepper', 'ground beef'],
 ['mineral water', 'honey', 'brownies'],
 ['turkey', 'eggs', 'cake', 'energy drink'],
 ['turkey',
  'burgers',
  'dessert wine',
  'ground beef',
  'soup',
  'salmon',
  'eggs',
  'gums',
  'tomato juice',
  'candy bars'],
 ['spaghetti', 'mineral water', 'chicken'],
 ['turkey', 'ground beef', 'carrots', 'french fries', 'melons'],
 ['mineral water', 'eggs', 'low fat yogurt'],
 ['turkey', 'cooking oil', 'shampoo'],
 ['spaghetti', 'hot dogs'],
 ['chocolate', 'green tea'],
 ['grated cheese',
  'pepper',
  'mineral water',
  'chocolate',
  'eggs',
  'cake',
  'mashed potato',
  'tomato juice'],
 ['chocolate'],
 ['spaghetti', 'olive oil', 'strong cheese', 'pancakes'],
 ['red wine', 'mineral water', 'soup', 'rice', 'cookies'],
 ['red wine', 'shrimp', 'spaghetti'],
 ['green tea'],
 ['mineral water', 'chicken', 'french fries', 'frozen smoothie'],
 ['muffins'],
 ['cake', 'chocolate'],
 ['fresh tuna',
  'tomatoes',
  'mineral water',
  'soup',
  'avocado',
  'meatballs',
  'olive oil'],
 ['turkey', 'french fries'],
 ['burgers',
  'turkey',
  'herb & pepper',
  'ground beef',
  'pancakes',
  'eggs',
  'light cream',
  'rice',
  'champagne',
  'fresh bread'],
 ['escalope'],
 ['chocolate', 'escalope', 'fresh bread'],
 ['ham',
  'spaghetti',
  'french wine',
  'vegetables mix',
  'chocolate',
  'french fries'],
 ['avocado', 'light mayo'],
 ['spaghetti', 'yams', 'butter', 'chocolate'],
 ['energy bar', 'eggs', 'french fries'],
 ['fresh tuna', 'barbecue sauce', 'eggplant'],
 ['energy drink'],
 ['whole wheat rice', 'french fries', 'hot dogs', 'green tea'],
 ['mineral water', 'chicken', 'green tea'],
 ['eggs', 'cake', 'mushroom cream sauce'],
 ['escalope'],
 ['antioxydant juice', 'escalope'],
 ['shrimp', 'spaghetti', 'french fries'],
 ['grated cheese', 'spaghetti', 'salmon', 'tomato juice'],
 ['spaghetti', 'green tea'],
 ['champagne', 'protein bar'],
 ['mineral water', 'avocado', 'chocolate'],
 ['tomatoes', 'champagne', 'green tea'],
 ['chicken', 'french fries', 'escalope'],
 ['frozen vegetables',
  'tomatoes',
  'eggs',
  'green tea',
  'frozen smoothie',
  'light mayo'],
 ['ground beef',
  'chicken',
  'cider',
  'green grapes',
  'honey',
  'chocolate',
  'french fries',
  'champagne',
  'frozen smoothie',
  'escalope'],
 ['french fries', 'champagne'],
 ['mineral water', 'soup'],
 ['frozen vegetables', 'spaghetti', 'milk', 'chocolate', 'babies food'],
 ['honey', 'whole wheat rice'],
 ['whole wheat rice', 'chicken', 'tomato juice'],
 ['pancakes'],

In [37]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.12/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [38]:
# Transaction encoding
from mlxtend.preprocessing import TransactionEncoder
te=TransactionEncoder()
te_array=te.fit_transform(transactions)

df=pd.DataFrame(te_array,columns=te.columns_)
df

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,True,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

# Apriori algo

In [39]:
from mlxtend.frequent_patterns import apriori,association_rules
freq_itemset=apriori(df,min_support=0.01,use_colnames=True)
freq_itemset.head()

    support          itemsets
0  0.020397         (almonds)
1  0.033329         (avocado)
2  0.010799  (barbecue sauce)
3  0.014265       (black tea)
4  0.011465      (body spray)

In [40]:
freq_itemset.shape

(257, 2)

In [41]:
# generate association rules
num_itemsets=len(freq_itemset)
rules=association_rules(freq_itemset,num_itemsets=num_itemsets,metric='confidence',min_threshold=0.2)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(avocado),(mineral water),0.033329,0.238368,0.011598,0.348000,1.459926,1.0,0.003654,1.168147,0.325896,0.044593,0.143943,0.198329
1,(burgers),(eggs),0.087188,0.179709,0.028796,0.330275,1.837830,1.0,0.013128,1.224818,0.499424,0.120941,0.183552,0.245256
2,(burgers),(french fries),0.087188,0.170911,0.021997,0.252294,1.476173,1.0,0.007096,1.108844,0.353384,0.093168,0.098160,0.190499
3,(burgers),(green tea),0.087188,0.132116,0.017464,0.200306,1.516139,1.0,0.005945,1.085270,0.372947,0.086526,0.078570,0.166248
4,(burgers),(milk),0.087188,0.129583,0.017864,0.204893,1.581175,1.0,0.006566,1.094717,0.402667,0.089812,0.086522,0.171377

In [42]:
rules.tail()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
157,"(spaghetti, mineral water)",(milk),0.059725,0.129583,0.015731,0.263393,2.032623,1.0,0.007992,1.181657,0.540294,0.090630,0.153731,0.192396
158,"(olive oil, spaghetti)",(mineral water),0.022930,0.238368,0.010265,0.447674,1.878079,1.0,0.004799,1.378954,0.478514,0.040892,0.274813,0.245370
159,"(olive oil, mineral water)",(spaghetti),0.027596,0.174110,0.010265,0.371981,2.136468,1.0,0.005460,1.315071,0.547034,0.053621,0.239585,0.215470
160,"(spaghetti, pancakes)",(mineral water),0.025197,0.238368,0.011465,0.455026,1.908923,1.0,0.005459,1.397557,0.488452,0.045479,0.284466,0.251562
161,"(mineral water, pancakes)",(spaghetti),0.033729,0.174110,0.011465,0.339921,1.952333,1.0,0.005593,1.251198,0.504819,0.058384,0.200766,0.202885

Generate strong rule

In [43]:
strong_rules=rules[(rules['confidence']>0.4) | (rules['lift']>1.2)]
strong_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(avocado),(mineral water),0.033329,0.238368,0.011598,0.348000,1.459926,1.0,0.003654,1.168147,0.325896,0.044593,0.143943,0.198329
1,(burgers),(eggs),0.087188,0.179709,0.028796,0.330275,1.837830,1.0,0.013128,1.224818,0.499424,0.120941,0.183552,0.245256
2,(burgers),(french fries),0.087188,0.170911,0.021997,0.252294,1.476173,1.0,0.007096,1.108844,0.353384,0.093168,0.098160,0.190499
3,(burgers),(green tea),0.087188,0.132116,0.017464,0.200306,1.516139,1.0,0.005945,1.085270,0.372947,0.086526,0.078570,0.166248
4,(burgers),(milk),0.087188,0.129583,0.017864,0.204893,1.581175,1.0,0.006566,1.094717,0.402667,0.089812,0.086522,0.171377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,"(spaghetti, mineral water)",(milk),0.059725,0.129583,0.015731,0.263393,2.032623,1.0,0.007992,1.181657,0.540294,0.090630,0.153731,0.192396
158,"(olive oil, spaghetti)",(mineral water),0.022930,0.238368,0.010265,0.447674,1.878079,1.0,0.004799,1.378954,0.478514,0.040892,0.274813,0.245370
159,"(olive oil, mineral water)",(spaghetti),0.027596,0.174110,0.010265,0.371981,2.136468,1.0,0.005460,1.315071,0.547034,0.053621,0.239585,0.215470
160,"(spaghetti, pancakes)",(mineral water),0.025197,0.238368,0.011465,0.455026,1.908923,1.0,0.005459,1.397557,0.488452,0.045479,0.284466,0.251562
161,"(mineral water, pancakes)",(spaghetti),0.033729,0.174110,0.011465,0.339921,1.952333,1.0,0.005593,1.251198,0.504819,0.058384,0.200766,0.202885

In [44]:
strong_rules.shape

(150, 14)

In [45]:
# Example transaction data
transactions = {
    'T1': ['A', 'B', 'D'],
    'T2': ['B', 'C'],
    'T3': ['A', 'B', 'C', 'E'],
    'T4': ['B', 'E'],
    'T5': ['A', 'B', 'C', 'E']
}

In [46]:
# Convert dictionary to DataFrame
transactions_df = pd.DataFrame.from_dict(transactions, orient='index').stack().reset_index(level=1, drop=True).to_frame(name='items')
transactions_df = transactions_df.reset_index().groupby('index')['items'].apply(list).reset_index(name='items')
transactions_df = pd.DataFrame(transactions_df['items'].tolist())

In [47]:
transactions_df

   0  1     2     3
0  A  B     D  None
1  B  C  None  None
2  A  B     C     E
3  B  E  None  None
4  A  B     C     E

In [50]:
!pip install pyECLAT
from pyECLAT import ECLAT

Collecting pyECLAT
  Downloading pyECLAT-1.0.2-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.12/dist-packages (from pyECLAT) (2.2.2)
Requirement already satisfied: numpy>=1.17.4 in /usr/local/lib/python3.12/dist-packages (from pyECLAT) (2.0.2)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from pyECLAT) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->pyECLAT) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->pyECLAT) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->pyECLAT) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->pyECLAT) (1.17.0)
Downloading pyECLAT-1.0.2-py3-none-any.whl (6.3 kB)
Installing collected packages: pyECLAT
Successfully installed pyECLAT-1.0.2

In [51]:
# Fit ECLAT
eclat = ECLAT(data=transactions_df)
frequent_itemsets = eclat.fit(min_support=0.4, min_combination=1, max_combination=3)
print("Frequent itemsets with support:\n", frequent_itemsets)

Combination 1 by 1

4it [00:00, 149.83it/s]

Combination 2 by 2

6it [00:00, 146.04it/s]

Combination 3 by 3

4it [00:00, 134.33it/s]

Frequent itemsets with support:
 ({'C': [1, 2, 4], 'E': [2, 3, 4], 'B': [0, 1, 2, 3, 4], 'A': [0, 2, 4], 'C & E': [2, 4], 'C & B': [1, 2, 4], 'C & A': [2, 4], 'E & B': [2, 3, 4], 'E & A': [2, 4], 'B & A': [0, 2, 4], 'C & E & B': [2, 4], 'C & E & A': [2, 4], 'C & B & A': [2, 4], 'E & B & A': [2, 4]}, {'C': 0.6, 'E': 0.6, 'B': 1.0, 'A': 0.6, 'C & E': 0.4, 'C & B': 0.6, 'C & A': 0.4, 'E & B': 0.6, 'E & A': 0.4, 'B & A': 0.6, 'C & E & B': 0.4, 'C & E & A': 0.4, 'C & B & A': 0.4, 'E & B & A': 0.4})

In [52]:
frequent_itemsets[1]

{'C': 0.6,
 'E': 0.6,
 'B': 1.0,
 'A': 0.6,
 'C & E': 0.4,
 'C & B': 0.6,
 'C & A': 0.4,
 'E & B': 0.6,
 'E & A': 0.4,
 'B & A': 0.6,
 'C & E & B': 0.4,
 'C & E & A': 0.4,
 'C & B & A': 0.4,
 'E & B & A': 0.4}

In [53]:
import pandas as pd
from mlxtend.frequent_patterns import association_rules

# The frequent itemsets provided by the user are in the second element of the tuple
frequent_itemsets_dict = frequent_itemsets[1]

# Convert the dictionary to a pandas DataFrame
freq_itemset_df = pd.DataFrame(list(frequent_itemsets_dict.items()), columns=['itemsets', 'support'])

# Convert the 'itemsets' column to frozensets to match the expected format for association_rules
freq_itemset_df['itemsets'] = freq_itemset_df['itemsets'].apply(lambda x: frozenset(x.split(' & ')))


# Generate association rules using mlxtend
rules_from_eclat = association_rules(freq_itemset_df, metric='confidence', min_threshold=0.7)

# Display the generated rules
display(rules_from_eclat)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(C),(B),0.6,1.0,0.6,1.0,1.000000,1.0,0.00,inf,0.000000,0.600000,0.0,0.800000
1,(E),(B),0.6,1.0,0.6,1.0,1.000000,1.0,0.00,inf,0.000000,0.600000,0.0,0.800000
2,(A),(B),0.6,1.0,0.6,1.0,1.000000,1.0,0.00,inf,0.000000,0.600000,0.0,0.800000
3,"(E, C)",(B),0.4,1.0,0.4,1.0,1.000000,1.0,0.00,inf,0.000000,0.400000,0.0,0.700000
4,"(E, C)",(A),0.4,0.6,0.4,1.0,1.666667,1.0,0.16,inf,0.666667,0.666667,1.0,0.833333
5,"(E, A)",(C),0.4,0.6,0.4,1.0,1.666667,1.0,0.16,inf,0.666667,0.666667,1.0,0.833333
6,"(C, A)",(E),0.4,0.6,0.4,1.0,1.666667,1.0,0.16,inf,0.666667,0.666667,1.0,0.833333
7,"(C, A)",(B),0.4,1.0,0.4,1.0,1.000000,1.0,0.00,inf,0.000000,0.400000,0.0,0.700000
8,"(E, A)",(B),0.4,1.0,0.4,1.0,1.000000,1.0,0.00,inf,0.000000,0.400000,0.0,0.700000